# Test against this version of Node.js
os: Visual Studio 2015

environment:
  matrix:
    - nodejs_version: "4.4.7"
    - nodejs_version: "6.3.0"

matrix:
  allow_failures:
    - nodejs_version: "6.3.0"

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Init submodules
  - git submodule update --init --recursive
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

# Build it
build_script:
  - mkdir build
  - cd build
  - if "%platform%" == "x86" cmake ..
  - if "%platform%" == "x64" cmake .. -G"Visual Studio 14 Win64"
  - cmake --build .

# Post-install test scripts.
test: off
